
import java.util.Iterator;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ravibansal
 */
public class jInternalFrame12 extends javax.swing.JInternalFrame {

    /**
     * Creates new form jInternalFrame12
     */
    save ob1;
    public jInternalFrame12(save ob) {
        initComponents();
        ob1=ob;
        String fn = JOptionPane.showInputDialog("Enter the book name to trace its history");
        Iterator<IssueBook> i12 = ob1.BookList.iterator();
	int flag=0;	
        while (i12.hasNext()) {
    	 IssueBook user = i12.next();
    	 if(user.getTitle().equalsIgnoreCase(fn)){
    		flag=1; 
             Iterator<BookStatistics> bs = user.Books.iterator();
    		int counj=0;	
    		 while (bs.hasNext()) {
    	    	 BookStatistics user1 = bs.next();
    	    	 counj++;
    	    	 jTextArea1.append(counj+". Friend: "+user1.getName()+"\n");
    	    	 jTextArea1.append("   Date Of Issue: "+user1.getDateOfIssue()+"\n");
                 jTextArea1.append("   Date Of Return: "+user1.getDateOfReturn()+"\n");
    	    	 jTextArea1.append("####################\n");
    		 }
         }
                }
        if(flag==0)
            jTextArea1.append("No Book Found\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
