
import java.util.Iterator;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ravibansal
 */
public class jInternalFrame2 extends javax.swing.JInternalFrame {

    /**
     * Creates new form jInternalFrame2
     */
    public jInternalFrame2(save ob) {
        initComponents();
        Iterator<IssueBook> ot = ob.BookList.iterator();
    	int count=0;
    	jTextArea1.setText("");
        while (ot.hasNext()) {
       	 IssueBook user = ot.next();
       	 jTextArea1.append("Book Id: "+user.getId()+"\n");
         jTextArea1.append("Book Title: "+user.getTitle()+"\n");
         jTextArea1.append("Year Of Publication: "+user.getYearOfPublication()+"\n");
         jTextArea1.append("Date Of Purchase: "+user.getDop()+"\n");
         jTextArea1.append("Price: : Rs"+user.getPrice()+"\n");
         jTextArea1.append("Publisher: "+user.getPublisher()+"\n");
         jTextArea1.append("#######################################\n");
       	 count++;
    	}if(count==0)
    		jTextArea1.append("There are no books to display");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
