
import java.util.Iterator;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ravibansal
 */
public class jInternalFrame6 extends javax.swing.JInternalFrame {

    /**
     * Creates new form jInternalFrame6
     */
    public jInternalFrame6(save ob) {
        initComponents();
        Iterator<IssueBook> i2 = ob.BookList.iterator();
    	String fn = JOptionPane.showInputDialog("Enter a keyword of a book");
        int count=0;
        jTextArea1.setText("");
        while (i2.hasNext()) {
       	 IssueBook user = i2.next();
       	  if (user.getTitle().contains(fn)) {
       	 jTextArea1.append("Book Id: "+user.getId()+"\n");
         jTextArea1.append("Book Title: "+user.getTitle()+"\n");
         jTextArea1.append("Year Of Publication: "+user.getYearOfPublication()+"\n");
         jTextArea1.append("Date Of Purchase: "+user.getDop()+"\n");
         jTextArea1.append("Price: : Rs"+user.getPrice()+"\n");
         jTextArea1.append("Publisher: "+user.getPublisher()+"\n");
         jTextArea1.append("#######################################\n");
       	 count++;
       	  }
    	}
        if(count==0)
            jTextArea1.append("No Books Found");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
